"""
Select the top-N Optuna trials whose unpenalized final_avg_reward meets a
threshold (default: 475 — the CartPole-v1 "solved" criterion) and export
each as a standard nested-YAML config usable by main.py / multi_seed_train.py.

Why threshold-based top-N (not just study.best_trial)? The single best trial
might have gotten lucky on its random seed. Retraining the top-N with
multiple seeds each (via multi_seed_train.py) and selecting the config with
the best mean ± std is more robust.

TODO: Add a "smallest" ranking option to see which candidates meet the threshold with
the smallest neural network size.

Filters:
  - state == COMPLETE (skips PRUNED / FAILED)
  - user_attrs["final_avg_reward"] >= --threshold

Sort key:
  - --rank-by final_avg  (default; ignores size/history penalties)
  - --rank-by objective  (uses trial.value, which has penalties applied)

Usage:
    # In-flight v2 study (defaults: --storage matches <neuron-type>-v2.db,
    # --study-name matches <neuron-type>):
    python select_top_candidates.py --neuron-type leaky --threshold 475 --top-n 3

    # Older finished study (override storage):
    python select_top_candidates.py --neuron-type leaky \\
        --storage sqlite:///optuna_studies/leaky.db \\
        --threshold 475 --top-n 3

    # Dry run — print the matching trials but do not write configs:
    python select_top_candidates.py --neuron-type leaky --top-n 3 --dry-run
"""

import argparse
from datetime import datetime
from pathlib import Path

import optuna
import yaml

from optimize import params_to_config_yaml


def storage_uri_for(neuron_type: str) -> str:
    """Default: the in-flight -v2 SQLite file."""
    return f"sqlite:///optuna_studies/{neuron_type}-v2.db"


def storage_filename_stem(storage_uri: str) -> str:
    """Extract 'leaky-v2' from 'sqlite:///optuna_studies/leaky-v2.db'.

    The exported config filename is derived from this so that v2 studies
    produce optimized-leaky-v2-topN.yaml (avoiding overwrite of older
    optimized-leaky-topN.yaml configs).
    """
    after_scheme = (
        storage_uri.split("///", 1)[-1] if "///" in storage_uri else storage_uri
    )
    return Path(after_scheme).stem


def _filter_metric(trial, metric: str):
    """Return the metric to filter/rank on, falling back as needed.

    'tail_iqm'  -> tail_iqm_avg_reward (preferred — IQM over the tail,
                   robust to single lucky/unlucky windows)
    'final_avg' -> final_avg_reward (legacy compatibility)
    'objective' -> trial.value (penalized objective)
    """
    if metric == "tail_iqm":
        return trial.user_attrs.get("tail_iqm_avg_reward")
    if metric == "final_avg":
        return trial.user_attrs.get("final_avg_reward")
    if metric == "objective":
        return trial.value
    raise ValueError(f"Unknown metric: {metric}")


def filter_and_rank(study, threshold: float, rank_by: str):
    """Return COMPLETE trials with rank_by metric >= threshold, sorted desc."""
    complete = study.get_trials(
        deepcopy=False, states=(optuna.trial.TrialState.COMPLETE,)
    )
    eligible = []
    skipped_no_attr = 0
    for t in complete:
        value = _filter_metric(t, rank_by)
        if value is None:
            skipped_no_attr += 1
            continue
        if value < threshold:
            continue
        eligible.append(t)

    if skipped_no_attr:
        print(
            f"  (note: skipped {skipped_no_attr} COMPLETE trials missing the "
            f"required metric — these are pre-instrumentation trials)"
        )

    eligible.sort(key=lambda t: _filter_metric(t, rank_by), reverse=True)
    return eligible


def export_trial_config(trial, output_path: Path, study_name: str, rank: int):
    config = params_to_config_yaml(trial.params)
    final_avg = trial.user_attrs.get("final_avg_reward")
    best_avg = trial.user_attrs.get("best_avg_reward")
    conv_ep = trial.user_attrs.get("convergence_episode")

    header_lines = [
        "# Auto-generated by select_top_candidates.py",
        f"# Study: {study_name}",
        f"# Trial: {trial.number} (rank {rank})",
        f"# Objective value (penalized): {trial.value:.2f}",
    ]
    if final_avg is not None:
        header_lines.append(f"# final_avg_reward: {final_avg:.2f}")
    if best_avg is not None:
        header_lines.append(f"# best_avg_reward:  {best_avg:.2f}")
    if conv_ep is not None:
        header_lines.append(f"# convergence_episode: {conv_ep}")
    header_lines.append(f"# Generated: {datetime.now().isoformat()}")
    header_lines.append("#")
    header_lines.append("# Multi-seed retrain:")
    header_lines.append(f"#   python multi_seed_train.py --config {output_path}")
    header = "\n".join(header_lines) + "\n\n"

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write(header)
        yaml.dump(config, f, default_flow_style=False, sort_keys=False)


def main():
    parser = argparse.ArgumentParser(
        description="Filter Optuna trials by threshold and export top-N configs."
    )
    parser.add_argument(
        "--neuron-type",
        type=str,
        required=True,
        choices=["leaky", "fractional", "bitshift", "bitshift-custom_slow_decay"],
        help="Neuron type. Drives default --storage and --study-name.",
    )
    parser.add_argument(
        "--study-name",
        type=str,
        default=None,
        help="Optuna study name inside the SQLite DB. If omitted and the DB "
        "contains exactly one study, it is auto-selected; otherwise the "
        "available study names are listed and the script exits.",
    )
    parser.add_argument(
        "--storage",
        type=str,
        default=None,
        help="SQLite URI. Defaults to sqlite:///optuna_studies/<neuron-type>-v2.db.",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=475.0,
        help="Minimum value of the --rank-by metric (default: 475 — "
        "CartPole-v1 solved criterion).",
    )
    parser.add_argument(
        "--top-n",
        type=int,
        default=3,
        help="Number of top trials to export (default: 3).",
    )
    parser.add_argument(
        "--rank-by",
        choices=["tail_iqm", "final_avg", "objective"],
        default="tail_iqm",
        help="Metric to filter and rank by. 'tail_iqm' (default, recommended) "
        "uses tail_iqm_avg_reward — the Interquartile Mean of "
        "trailing-100 averages over the final 25%% of training. "
        "'final_avg' is the legacy metric (last 100 episodes only). "
        "'objective' uses trial.value with penalties.",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="configs",
        help="Where to write optimized-<stem>-topN.yaml configs (default: configs/).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print matching trials but do not write any config files.",
    )
    args = parser.parse_args()

    storage = args.storage or storage_uri_for(args.neuron_type)
    stem = storage_filename_stem(storage)

    available = optuna.get_all_study_names(storage=storage)
    if not available:
        print(f"\nNo studies found in storage: {storage}")
        return

    if args.study_name is None:
        if len(available) == 1:
            study_name = available[0]
            print(f"  (auto-selected the single study in this DB: {study_name!r})")
        else:
            print(f"\nMultiple studies in {storage}:")
            for n in available:
                print(f"  - {n}")
            print(
                "\nPick one with --study-name <name>. "
                "(There is no fixed convention across DBs; older DBs use "
                "timestamped names.)"
            )
            return
    else:
        study_name = args.study_name
        if study_name not in available:
            print(f"\nStudy {study_name!r} not in {storage}. Available studies:")
            for n in available:
                print(f"  - {n}")
            return

    print(f"Loading Optuna study:")
    print(f"  study_name : {study_name}")
    print(f"  storage    : {storage}")
    print(f"  threshold  : final_avg_reward >= {args.threshold}")
    print(f"  rank_by    : {args.rank_by}")
    print(f"  top_n      : {args.top_n}")

    study = optuna.load_study(study_name=study_name, storage=storage)
    eligible = filter_and_rank(study, args.threshold, args.rank_by)

    if not eligible:
        print(f"\nNo COMPLETE trials with final_avg_reward >= {args.threshold}.")
        return

    print(f"\nMatched {len(eligible)} trials. Top {min(args.top_n, len(eligible))}:")
    print(
        f"{'rank':>4}  {'trial':>5}  {'objective':>10}  "
        f"{'tail_iqm':>9}  {'final_avg':>10}  {'best_avg':>9}  {'conv_ep':>8}"
    )
    for i, t in enumerate(eligible[: args.top_n], start=1):
        final_avg = t.user_attrs.get("final_avg_reward")
        best_avg = t.user_attrs.get("best_avg_reward")
        tail_iqm = t.user_attrs.get("tail_iqm_avg_reward")
        conv = t.user_attrs.get("convergence_episode")
        conv_str = f"{conv}" if conv is not None else "-"
        print(
            f"{i:>4}  {t.number:>5}  {t.value:>10.2f}  "
            f"{(tail_iqm if tail_iqm is not None else 0):>9.2f}  "
            f"{(final_avg if final_avg is not None else 0):>10.2f}  "
            f"{(best_avg if best_avg is not None else 0):>9.2f}  "
            f"{conv_str:>8}"
        )

    if args.dry_run:
        print("\n(dry-run: no configs written)")
        return

    output_dir = Path(args.output_dir)
    print()
    for rank, trial in enumerate(eligible[: args.top_n], start=1):
        out_path = output_dir / f"optimized-{stem}-top{rank}.yaml"
        export_trial_config(trial, out_path, study_name, rank)
        print(f"  wrote: {out_path}")


if __name__ == "__main__":
    main()
